---
- name: Copying Dockerfile
  hosts: test
  become: true

  tasks:
    - name: Copy file from 
      ansible.builtin.copy:
        src: /home/ktk/mongo/docker/Dockerfile
        dest: /home/ktk/playbooks/Dockerfile  
          
