---
- name: Copying Dockerfile
  hosts: localhost
  become: true

  tasks:
    - name: Copy file from 
      ansible.builtin.copy:
        src: /home/ktk/mongo/docker/Dockerfile
        dest: /home/ktk/data/Dockerfile
        owner: jenkins
        group: jenkins
        mode: 0777
        remote_src: yes 
          
