apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-pod
spec:
  containers:
    - image: httpd:2.4
      name: httpd
      ports:
        - protocol: TCP
          containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  type: NodePort
  selector:
    app: my-pod
  ports:
    - port: 80
      targetPort: 80
